[workspace]
resolver = "2"
members = [
    "crates/oryn-common",
    "crates/oryn-core",
    "crates/oryn-engine",
    "crates/oryn-scanner",
    "crates/oryn-e",
    "crates/oryn-h",
    "crates/oryn-r",
    "crates/oryn",
    "crates/oryn-native",
    "crates/oryn-webidl",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
